name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ryansheldrake/jenkins:2.60.3
      
  scan_job:
    runs-on: ubuntu-18.04
    env:
      LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
      LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
    steps:
#       - name: pull
#         shell: bash
#         run: |
#           docker pull image_name:image_tag #Pull the image to scan

      - name: scan
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get -y install curl
          curl -L https://github.com/lacework/lacework-vulnerability-scanner/releases/latest/download/lw-scanner-linux-amd64 -o lw-scanner
          chmod +x lw-scanner
          ./lw-scanner image evaluate ryansheldrake/jenkins 2.60.3 --save --build-id ${{ github.run_id }}
