name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: LW-GH-Env
    env:
      LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
      LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ryansheldrake/jenkins:2.60.3
    - name: scan
      shell: bash
      run: |
          sudo apt-get update
          sudo apt-get -y install curl
          curl -L https://github.com/lacework/lacework-vulnerability-scanner/releases/download/v0.6.1/lw-scanner-linux-386 -o lw-scanner
          chmod +x lw-scanner
          ./lw-scanner image evaluate jenkins 2.60.3 --save --build-id ${{ github.run_id }}
      
